version: "3.9"
services:
    web:
        build: .
        command: daphne --bind 0.0.0.0 -p 8000 api.asgi:application
        ports:
            - 8000:8000
        restart: on-failure
        image: xx
