# Generated by Django 4.1.7 on 2023-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teaminvitation",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("store_clerk", "Store Clerk")],
                default="store_clerk",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("store_clerk", "Store Clerk")],
                default="admin",
                max_length=11,
            ),
        ),
    ]
