# Generated by Django 4.1.7 on 2023-11-25 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_customer_product_productcategory_productitem_sales_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.IntegerField(default=1)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="api.business",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="productitem",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_items",
                to="api.vendor",
            ),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name="Sales",
            new_name="Sale",
        ),
        migrations.DeleteModel(
            name="SalesItem",
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="api.productitem",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_items",
                to="api.sale",
            ),
        ),
    ]
