# Generated by Django 4.1.7 on 2023-11-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_items",
                to="api.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_items",
                to="api.vendor",
            ),
        ),
    ]
