# Generated by Django 4.1.7 on 2023-11-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_productitem_category_alter_productitem_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="qty_accepted",
        ),
        migrations.RemoveField(
            model_name="order",
            name="qty_defected",
        ),
        migrations.RemoveField(
            model_name="order",
            name="qty_delayed",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="qty_accepted",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="qty_defected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="qty_delayed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="qty_ordered",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="expiring_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productitem",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
