# Generated by Django 4.1.7 on 2023-11-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_order_qty_accepted_remove_order_qty_defected_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="cost_price",
            new_name="total_cost_price",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="total_cost_price",
            new_name="unit_cost_price",
        ),
        migrations.RenameField(
            model_name="saleitem",
            old_name="cost_price",
            new_name="selling_price",
        ),
        migrations.AddField(
            model_name="productitem",
            name="lead_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productitem",
            name="name",
            field=models.CharField(default="product_item01", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="total_selling_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="unit_selling_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="placement_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
