# Generated by Django 4.1.7 on 2023-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_productitem_size_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="qdp_rating",
            field=models.FloatField(default=0),
        ),
    ]
