# Generated by Django 4.1.7 on 2023-11-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_vendor_completed_orders_vendor_total_lead_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
