# Generated by Django 4.1.7 on 2023-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_saleitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="lead_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="total_qdp_rating",
            field=models.FloatField(default=0),
        ),
    ]
