# Generated by Django 4.1.7 on 2023-11-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_vendor_lead_time_vendor_total_qdp_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_order_items",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_sale_items",
                to="api.sale",
            ),
        ),
    ]
