# Generated by Django 4.1.7 on 2024-01-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
    ]
