# Generated by Django 4.1.7 on 2024-01-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="eoq",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("reorder", "Reorder"),
                    ("in_stock", "In Stock"),
                    ("out_of_stock", "Out Of Stock"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
    ]
