# Generated by Django 4.1.7 on 2024-01-09 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_remove_productitem_status_productitem_annual_demand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="business",
        ),
    ]
